name: using action

on: push

jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: printing folder
        run: ls
        
    